name: Python type check
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download submodules
        run: git submodule update --init --recursive
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install pip -U
          pip install mypy
      - name: Lint with mypy
        run: mypy -m apimd
